language: c

dist: xenial

compiler:
  - gcc
  - clang

env:
  matrix:
    - BUILD_TYPE=debug
      ENABLE_COVERAGE=OFF
      CONFIGURE_FLAGS="--enable-mcsat"
    - BUILD_TYPE=debug
      ENABLE_COVERAGE=OFF
      CONFIGURE_FLAGS="--enable-thread-safety"
    - BUILD_TYPE=release
      ENABLE_COVERAGE=OFF
      CONFIGURE_FLAGS="--enable-mcsat"
    - BUILD_TYPE=release
      ENABLE_COVERAGE=OFF
      CONFIGURE_FLAGS="--enable-thread-safety"
    - BUILD_TYPE=gcov
      ENABLE_COVERAGE=ON
      CONFIGURE_FLAGS="--enable-mcsat"

# command to install dependencies
install:
  - sudo apt-get update
  - sudo apt-get install -y libgmp-dev gperf
  - sudo apt-get install -y python-pip
  - sudo apt-get install -y lcov
  - gem install coveralls-lcov

#tests
script:
  - ./.travis/build.sh

after_success:
  - if [[ $ENABLE_COVERAGE == ON ]]; then
      lcov --directory build --base-directory src --capture --output-file coverage.info;
      coveralls-lcov coverage.info;
    fi
